# AWS CodeBuild が読み込む buildspec のバージョンです。
version: 0.2

# ビルド全体で使う環境変数を定義します。
env:
  variables:
    # Docker BuildKit を有効にして、Docker イメージのビルド機能を拡張します。
    DOCKER_BUILDKIT: "1"

# CodeBuild では pre_build -> build -> post_build の順番で commands が実行されます。
phases:
  # ビルド前の準備を行うフェーズです。
  pre_build:
    commands:
      - echo ===== pre build phase =====

      # Docker Content Trust を有効にし、署名されたイメージを扱う設定にします。
      - export DOCKER_CONTENT_TRUST=1

      # ECR のリポジトリ URL と、コミット ID から作るイメージタグを準備します。
      - export ECR_REPOS_DOMAIN=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export ECR_REPOS_URI=${ECR_REPOS_DOMAIN}/${APP_NAME}
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo ECR_REPOS_URI=${ECR_REPOS_URI}

  # Docker イメージをビルドし、ECR に push するためのタグを付けるフェーズです。
  build:
    commands:
      - echo ===== build phase =====
      - echo Docker Build started on `date`
      - echo Building the Docker image...
      # Dockerfile を使って、アプリケーションの Docker イメージを作成します。
      - docker buildx build -t ${APP_NAME}:latest .
      # 作成したイメージに、ECR へ push するための名前とタグを付けます。
      - docker image tag ${APP_NAME}:latest ${ECR_REPOS_URI}:${IMAGE_TAG}
      - docker image ls
      - echo Completed the ${APP_NAME} Docker image build.

      # 以降の push 処理に備えて Docker Content Trust を無効にします。
      - export DOCKER_CONTENT_TRUST=0

  # ビルド後に、Docker イメージを ECR へ push し、デプロイ用ファイルを作成するフェーズです。
  post_build:
    commands:
      - echo ===== post build phase =====
      - echo Logging in to Amazon ECR.
      # CodeBuild から ECR に Docker イメージを push できるようにログインします。
      - aws ecr get-login-password | docker login --username AWS --password-stdin "https://${ECR_REPOS_DOMAIN}"
      - echo Docker Image ${APP_NAME} pushing to ECR on `date`
      # build フェーズで作成した Docker イメージを ECR に push します。
      - docker image push ${ECR_REPOS_URI}:${IMAGE_TAG}
      # ECS がどのコンテナイメージを使うかを知るためのファイルを作成します。
      - echo '[{"name":"app","imageUri":"'$ECR_REPOS_URI':'$IMAGE_TAG'"}]'  > imagedefinitions.json

# CodeBuild の成果物として、CodePipeline/ECS デプロイで使うファイルを出力します。
artifacts:
  files:
    - imagedefinitions.json
